DigitalRepublicTesteTech/Models/ErrorViewModel.cs
namespace DigitalRepublicTesteTech.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DigitalRepublicTesteTech/Models/IParede.cs
namespace DigitalRepublicTesteTech.Models
{
    public interface IParede
    {
        public double? Comprimento { get; set; }
        public double? Altura { get; set; }
        public int? QntPortas { get; set; }
        public int? QntJanelas { get; set; }

    }
}

DigitalRepublicTesteTech/Models/ParedeModel.cs
using DigitalRepublicTesteTech.Helpers;
using System.ComponentModel.DataAnnotations;

namespace DigitalRepublicTesteTech.Models
{
    public class ParedeModel : IParede
    {
        public ParedeModel()
        {
        }
        public ParedeModel(double comprimento, double altura, int qntPortas, int qntJanelas)
        {
            this.Comprimento = comprimento;
            this.Altura = altura;
            this.QntPortas = qntPortas;
            this.QntJanelas = qntJanelas;
        }

        [Required(ErrorMessage = "O campo Comprimento é obrigatório")]
        [RegularExpression(@"^([0-9]+(\,?[0-9]?[0-9]?)?)", ErrorMessage = "Campo precisa seguir o formato decimal, utilizando vírgula como separador")]
        public double? Comprimento { get; set; }

        [Required(ErrorMessage = "O campo Altura é obrigatório")]
        [RegularExpression(@"^([0-9]+(\,?[0-9]?[0-9]?)?)", ErrorMessage = "Campo precisa seguir o formato decimal, utilizando vírgula como separador.")]
        [ValidationAlturaPortas("QntPortas", ErrorMessage = "Quando houverem portas, a altura da parede deve ser no mínimo de 2,20m")]
        public double? Altura { get; set; }

        [Required(ErrorMessage = "O campo Quantidade de Portas é obrigatório")]
        public int? QntPortas { get; set; }

        [Required(ErrorMessage = "O campo Quantidade de Janelas é obrigatório")]
        public int? QntJanelas { get; set; }

        [ValidationAreaParede]
        public double AreaQuePodeSerPintada { get; set; }
        
        [ValidationAreaTotalJanelasEPortas("Comprimento", "Altura")]
        public double AreaTotalJanelaEPortas { get; set; }

        public double CalcularAreaJanelasEPortas()
        {
            if(QntJanelas != null && QntPortas != null)
            {
            this.AreaTotalJanelaEPortas = (2.4 * this.QntJanelas.Value) + (1.52 * this.QntPortas.Value);
            }
            return this.AreaTotalJanelaEPortas;
        }

        public double CalcularAreaParede()
        {
            if (Altura != null && Comprimento != null && AreaTotalJanelaEPortas != null)
                this.AreaQuePodeSerPintada = (Altura.Value * Comprimento.Value) - AreaTotalJanelaEPortas;
            return this.AreaQuePodeSerPintada;
        }

        

    }
}

DigitalRepublicTesteTech/Models/SalaModel.cs
namespace DigitalRepublicTesteTech.Models
{
    public class SalaModel
    {
        public SalaModel()
        {

        }
        public SalaModel(ParedeModel paredeA, ParedeModel paredeB, ParedeModel paredeC, ParedeModel paredeD)
        {
            this.ParedeA = paredeA;
            this.ParedeB = paredeB;
            this.ParedeC = paredeC;
            this.ParedeD = paredeD;
            
        }

        public ParedeModel ParedeA { get; set; }
        public ParedeModel ParedeB { get; set; }
        public ParedeModel ParedeC { get; set; }
        public ParedeModel ParedeD { get; set; }

        public double AreaTotalJanelasEPortas { get; set; }
        public double AreaTotalQuePodeSerPintada { get; set; }

        public int TotalLatas18 { get; set; }
        public int TotalLatas3L600 { get; set; }
        public int TotalLatas2L5 { get; set; }
        public int TotalLatas0L5 { get; set; }

        public bool CalculoRealizado { get; set; } = false;


        public void CalcularLatasTotal()
        {
            CalcularLatas();
            this.CalculoRealizado = true;
        }

        public void CalcularAreaTotalJanelasEPortas()
        {
            this.AreaTotalJanelasEPortas = ParedeA.CalcularAreaJanelasEPortas() +
                                           ParedeB.CalcularAreaJanelasEPortas() +
                                           ParedeC.CalcularAreaJanelasEPortas() +
                                           ParedeD.CalcularAreaJanelasEPortas();
        }

        public void CalcularAreaTotalQuePodeSerPintada()
        {
            this.AreaTotalQuePodeSerPintada = ParedeA.CalcularAreaParede() +
                                              ParedeB.CalcularAreaParede() +
                                              ParedeC.CalcularAreaParede() +
                                              ParedeD.CalcularAreaParede();
        }

        public void CalcularLatas()
        {
            var qtd = AreaTotalQuePodeSerPintada;

            while (qtd > 0)
            {
                while (qtd >= 90)
                {
                    this.TotalLatas18++;
                    qtd -= 90;
                }
                while (qtd >= 18)
                {
                    this.TotalLatas3L600++;
                    qtd -= 18;
                }
                while (qtd >= 12.5)
                {
                    this.TotalLatas2L5++;
                    qtd -= 12.5;
                }
                while (qtd >= 2.5 || qtd <= 2.5 && qtd>=0)
                {
                    this.TotalLatas0L5++;
                    qtd -= 2.5;
                }
            }

        }

    }
}

DigitalRepublicTesteTech/Controllers/CalculoTintaController.cs
using DigitalRepublicTesteTech.Models;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace DigitalRepublicTesteTech.Controllers
{
    public class CalculoTintaController : Controller
    {
        
        
        [HttpGet]
        public IActionResult CalcularTinta()
        {
            return View();
        }


        [HttpPost]
        public IActionResult CalcularTinta(SalaModel sala)
        {

            sala.CalcularAreaTotalJanelasEPortas();
            sala.CalcularAreaTotalQuePodeSerPintada();

            ModelState.ClearValidationState(nameof(sala));
            ModelState.Clear();
            TryValidateModel(sala);
            
            if (ModelState.IsValid)
            {

                sala.CalcularLatasTotal();

                return View(sala);
            }

            return View(sala);
        }

    }
}

DigitalRepublicTesteTech/Views/CalculoTinta/calcularTinta.cshtml
@model DigitalRepublicTesteTech.Models.SalaModel;

@{
    ViewData["Title"] = "Calcular Tinta";
    Layout = "_Layout";
}
<h1> Calculadora de Tinta</h1>
<div>
    <form asp-action="CalcularTinta" asp-controller="CalculoTinta" asp-route-culture="pt-BR">

        <table>
            @*PAREDE A*@
            <thead>
                <tr><h4>Parede A</h4></tr>
                <tr>
                    <th>Comprimento</th>
                    <th>Altura</th>
                    <th>Quantidade de Portas (área 1,52m² cada)</th>
                    <th>Quantidade de Janelas (área 2,4m² cada)</th>
                </tr>
            </thead>
            <tbody>
                @*linha Inputs*@
                <tr>
                    <td>
                        <input asp-for="ParedeA.Comprimento" />
                    </td>
                    <td>
                        <input asp-for="ParedeA.Altura" />
                    </td>
                    <td>
                        <input asp-for="ParedeA.QntPortas" />
                    </td>
                    <td>
                        <input asp-for="ParedeA.QntJanelas" />
                    </td>
                </tr>
                @*linha validations*@
                <tr>
                    <td>
                        <span class="validations" asp-validation-for="ParedeA.Comprimento"></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeA.Altura"></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeA.QntPortas"></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeA.QntJanelas"></span>
                    </td>
                </tr>
            </tbody>
        </table>

        <table>
            @*PAREDE B*@
            <thead>
                <tr><h4>Parede B</h4></tr>
                <tr>
                    <th>Comprimento</th>
                    <th>Altura</th>
                    <th>Quantidade de Portas (área 1,52m² cada)</th>
                    <th>Quantidade de Janelas (área 2,4m² cada)</th>
                </tr>
            </thead>
            <tbody>
                @*linha Inputs*@
                <tr>
                    <td>
                        <input asp-for="ParedeB.Comprimento" />
                    </td>
                    <td>
                        <input asp-for="ParedeB.Altura" />
                    </td>
                    <td>
                        <input asp-for="ParedeB.QntPortas" />
                    </td>
                    <td>
                        <input asp-for="ParedeB.QntJanelas" />
                    </td>
                </tr>
                @*linha validations*@
                <tr>
                    <td>
                        <span class="validations" asp-validation-for="ParedeB.Comprimento"></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeB.Altura"></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeB.QntPortas"></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeB.QntJanelas"></span>
                    </td>
                </tr>
            </tbody>
        </table>

        <table>
            @*PAREDE C*@
            <thead>
                <tr><h4>Parede C</h4></tr>
                <tr>
                    <th>Comprimento</th>
                    <th>Altura</th>
                    <th>Quantidade de Portas (área 1,52m² cada)</th>
                    <th>Quantidade de Janelas (área 2,4m² cada)</th>
                </tr>
            </thead>
            <tbody>
                @*linha Inputs*@
                <tr>
                    <td>
                        <input asp-for="ParedeC.Comprimento" />
                    </td>
                    <td>
                        <input asp-for="ParedeC.Altura" />
                    </td>
                    <td>
                        <input asp-for="ParedeC.QntPortas" />
                    </td>
                    <td>
                        <input asp-for="ParedeC.QntJanelas" />
                    </td>
                </tr>
                @*linha validations*@
                <tr>
                    <td>
                        <span class="validations" asp-validation-for="ParedeC.Comprimento"></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeC.Altura" ></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeC.QntPortas" ></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeC.QntJanelas" ></span>
                    </td>
                </tr>
            </tbody>
        </table>

        <table>
            @*PAREDE D*@
            <thead>
                <tr><h4>Parede D</h4></tr>
                <tr>
                    <th>Comprimento</th>
                    <th>Altura</th>
                    <th>Quantidade de Portas (área 1,52m² cada)</th>
                    <th>Quantidade de Janelas (área 2,4m² cada)</th>
                </tr>
            </thead>
            <tbody>
                @*linha Inputs*@
                <tr>
                    <td>
                        <input asp-for="ParedeD.Comprimento" />
                    </td>
                    <td>
                        <input asp-for="ParedeD.Altura" />
                    </td>
                    <td>
                        <input asp-for="ParedeD.QntPortas" />
                    </td>
                    <td>
                        <input asp-for="ParedeD.QntJanelas" />
                    </td>
                </tr>
                @*linha validations*@
                <tr>
                    <td>
                        <span class="validations" asp-validation-for="ParedeD.Comprimento" ></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeD.Altura" ></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeD.QntPortas" ></span>
                    </td>
                    <td>
                        <span class="validations" asp-validation-for="ParedeD.QntJanelas" ></span>
                    </td>
                </tr>
            </tbody>
        </table>

        <div id="listaErros" asp-validation-summary="All" ></div>

        <div id="btnDiv">
            <input id="btnSubmit" type="submit" value="Calcular" />
        </div>



    </form>

    @if (Model != null && Model.CalculoRealizado)
    {
        <div>
            <p id="txtResultado"> Este é o total de latas que serão necessárias para pintar a sala:</p>
            <table aria-labelledby="tableLabel">
                <thead>
                    <tr>
                        <th>18 Litros</th>
                        <th>3,6 Litros</th>
                        <th>2,5 Litros</th>
                        <th>0,5 LItros</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.TotalLatas18</td>
                        <td>@Model.TotalLatas3L600</td>
                        <td>@Model.TotalLatas2L5</td>
                        <td>@Model.TotalLatas0L5</td>

                    </tr>
                </tbody>
            </table>
        </div>
    }

</div>

DigitalRepublicTesteTech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DigitalRepublic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DigitalRepublicTesteTech.styles.css" asp-append-version="true" />
</head>
<body style="background-color:lightgray;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="CalculoTinta" asp-action="CalcularTinta">DigitalRepublic</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="CalculoTinta" asp-action="CalcularTinta">Calcular</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DigitalRepublicTesteTech
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>